version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    commit-message:
      prefix: "deps(cargo)"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
